import Head from "next/head";
import Image from "next/image";
import React from "react";
import profilePic from "../public/calender-icon.svg";
import refershicon from "../public/refresh-icon.svg";
import notbookicon from "../public/notbook-icon.svg";
import notebook1icon from "../public/notebook1-icon.svg";
import listicon from "../public/list-icon.svg";
import playicon from "../public/play-icon.svg";
import anroidapp from "../public/anroid-app.png";
import appleapp from "../public/apple-app.png";
import bannerimg from "../public/banner-img.png";
import iphonepic from "../public/iPhone13ProMax.png";
import Slider from "react-slick";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Accordion from "../Components/Accordion/Accordion";
import styles from "../styles/Home.module.css";

export default function Home() {
  var settings = {
    dots: true,
  };
  return (
    <div className={styles.body}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="bg-blue">
        <div className={styles.containerlg}>
          <div className="flex items-center">
            <div className="w-1/2">
              <div className={styles.sitettl}>
                <b>Me</b>volve
              </div>
            </div>
            <div className="flex justify-end w-1/2">
              <ul className={`flex items-center ${styles.menu}`}>
                <li>
                  <a href="#" className={styles.active}>
                    Home
                  </a>
                </li>
                <li>
                  <a href="#">Features</a>
                </li>
                <li>
                  <a href="#">Pricing</a>
                </li>
                <li>
                  <a href="#">Contact Us</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </header>

      <main className={styles.main}>
        <div className={styles.container}>
          <div className={` pt-75 pb-99  ${styles["banner"]}`}>
            <Slider {...settings}>
              <div>
                <div className="grid grid-cols-12 gap-4 items-center">
                  <div className="col-span-6 text-center ">
                    <h1>Automate self-development</h1>
                    <div className={`text-dgray1 mb-30 ${styles.textsm}`}>
                      Evolve daily by efficiently managing your time, thoughts,
                      tasks and routines in a simple app.
                    </div>
                    <div className={styles.btnrow}>
                      <a
                        href="#"
                        className={`${styles["btn"]} ${styles["video-btn"]}`}
                      >
                        <Image
                          src={playicon}
                          alt="Picture of the author"
                          className="inline-block"
                        />
                        watch video
                      </a>
                    </div>
                    <div
                      className={`flex justify-between mt-30 ${styles["mx338"]}`}
                    >
                      <Image
                        src={appleapp}
                        alt="
                      Apple app"
                      />
                      <Image src={anroidapp} alt="google play app" />
                    </div>
                  </div>
                  <div className="col-span-6 text-center">
                    <Image src={bannerimg} alt="google play app" />
                  </div>
                </div>
              </div>
              <div>
                <div className="grid grid-cols-12 gap-4 items-center ">
                  <div className="col-span-6 text-center ">
                    <h1>Automate self-development</h1>
                    <div className={`text-dgray1 mb-30 ${styles.textsm}`}>
                      Evolve daily by efficiently managing your time, thoughts,
                      tasks and routines in a simple app.
                    </div>
                    <div className={styles.btnrow}>
                      <a
                        href="#"
                        className={`${styles["btn"]} ${styles["video-btn"]}`}
                      >
                        <Image src={playicon} alt="Picture of the author" />
                        watch video
                      </a>
                    </div>
                    <div
                      className={`flex justify-between mt-30 ${styles["mx338"]}`}
                    >
                      <Image
                        src={appleapp}
                        alt="
                      Apple app"
                      />
                      <Image src={anroidapp} alt="google play app" />
                    </div>
                  </div>
                  <div className="col-span-6 text-center">
                    <Image src={bannerimg} alt="google play app" />
                  </div>
                </div>
              </div>
              <div>
                <div className="grid grid-cols-12 gap-4 items-center">
                  <div className="col-span-6 text-center ">
                    <h1>Automate self-development</h1>
                    <div className={`text-dgray1 mb-30 ${styles.textsm}`}>
                      Evolve daily by efficiently managing your time, thoughts,
                      tasks and routines in a simple app.
                    </div>
                    <div className={styles.btnrow}>
                      <a
                        href="#"
                        className={`${styles["btn"]} ${styles["video-btn"]}`}
                      >
                        <Image src={playicon} alt="Picture of the author" />
                        watch video
                      </a>
                    </div>
                    <div
                      className={`flex justify-between mt-30 ${styles["mx338"]}`}
                    >
                      <Image
                        src={appleapp}
                        alt="
                      Apple app"
                      />
                      <Image src={anroidapp} alt="google play app" />
                    </div>
                  </div>
                  <div className="col-span-6 text-center">
                    <Image src={bannerimg} alt="google play app" />
                  </div>
                </div>
              </div>
            </Slider>
          </div>
        </div>

        <div className={`bg-lgray pt-28 pb-32 ${styles["applist"]}`}>
          <h1 className="text-fs20 text-lbalck text-center">
            One App To Rule Them All
          </h1>
          <div className={`flex justify-between	 ${styles.container}`}>
            <div className={styles.box}>
              <Image src={profilePic} alt="To-Do List" />
              <span>To-Do List</span>
            </div>
            <div className={styles.box}>
              <Image src={refershicon} alt="Habit Tracker" />
              <span>Habit Tracker</span>
            </div>
            <div className={styles.box}>
              <Image src={notbookicon} alt="Picture of the author" />
              <span>Journaling</span>
            </div>
            <div className={styles.box}>
              <Image src={notebook1icon} alt="Picture of the author" />
              <span>Notes</span>
            </div>
            <div className={styles.box}>
              <Image src={listicon} alt="Picture of the author" />
              <span>List</span>
            </div>
          </div>
        </div>

        <div className={`${styles["twocol"]} ${styles["leftimg"]}`}>
          <div className={styles.container}>
            <div className="grid grid-cols-12 gap-4 items-center py-48">
              <div className={`col-span-4 ${styles["leftcol"]}`}>
                <Image src={iphonepic} alt="To-Do List" />
              </div>
              <div className="col-span-8">
                <h2>Customize the way you like</h2>
                <div className={styles.accordianbox}>
                  <Accordion />
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
