import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React from "react";
import profilePic from "../public/calendericon.jpg";

export default function Home() {
  return (
    <div className={styles.body}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.container}>
          <div className="flex items-center">
            <div className="w-1/2">
              <div className={styles.sitettl}>
                <b>Me</b>volve
              </div>
            </div>
            <div className="flex justify-end w-1/2">
              <ul className="flex items-center">
                <li>
                  <a href="#" className="active">
                    Home
                  </a>
                </li>
                <li>
                  <a href="#">Features</a>
                </li>
                <li>
                  <a href="#">Pricing</a>
                </li>
                <li>
                  <a href="#">Contact Us</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </header>
      <main className={styles.main}>
        <div className={`${styles["bggray"]} ${styles["applist"]}`}>
          <div className={`flex justify-between	 ${styles.container}`}>
            <div className={styles.box}>
              <Image src={profilePic} alt="Picture of the author" />
              <span>To-Do List</span>
            </div>
            <div className={styles.box}>
              <Image src={profilePic} alt="Picture of the author" />
              <span>Habit Tracker</span>
            </div>
            <div className={styles.box}>
              <Image src={profilePic} alt="Picture of the author" />
              <span>Journaling</span>
            </div>
            <div className={styles.box}>
              <Image src={profilePic} alt="Picture of the author" />
              <span>Notes</span>
            </div>
            <div className={styles.box}>
              <Image src={profilePic} alt="Picture of the author" />
              <span>List</span>
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
